Repository NorskRegnesentral/skchange, pull requests merged in 2024-12, with the labels that each got.

#47 Remove mutable objects from defaults
  skchange/anomaly_detectors/capa.py
  skchange/anomaly_detectors/circular_binseg.py
  skchange/anomaly_detectors/mvcapa.py
  skchange/anomaly_scores/from_cost.py
  skchange/change_detectors/moving_window.py
  skchange/change_detectors/pelt.py
  skchange/change_detectors/seeded_binseg.py
  skchange/change_detectors/tests/test_change_detectors.py
  skchange/change_detectors/tests/test_moving_window.py
  skchange/change_detectors/tests/test_pelt.py
  skchange/change_detectors/tests/test_seeded_binseg.py
  skchange/change_scores/from_cost.py
  skchange/datasets/generate.py
  skchange/tests/test_all_detectors.py
  skchange/tests/test_all_estimators.py
  skchange/tests/test_all_interval_evaluators.py
Labels: bug

#38 Specialize gaussian cov change score to add Bartlett correction
  .pre-commit-config.yaml
  pyproject.toml
  skchange/anomaly_detectors/anomalisers.py
  skchange/anomaly_detectors/circular_binseg.py
  skchange/anomaly_detectors/tests/test_capa.py
  skchange/anomaly_scores/from_cost.py
  skchange/change_scores/__init__.py
  skchange/change_scores/multivariate_gaussian_score.py
  skchange/change_scores/tests/test_all_change_scores.py
  skchange/change_scores/tests/test_gaussian_cov_score.py
  skchange/costs/__init__.py
  skchange/costs/multivariate_gaussian_cost.py
  skchange/costs/tests/test_gaussian_cov_cost.py
  skchange/tests/test_all_interval_evaluators.py
  skchange/utils/validation/data.py
Labels: enhancement

#53 [DOC] Update docs for upcoming version 0.10
  skchange/anomaly_detectors/anomalisers.py
  skchange/anomaly_detectors/base.py
  skchange/anomaly_detectors/capa.py
  skchange/anomaly_detectors/circular_binseg.py
  skchange/anomaly_detectors/mvcapa.py
  skchange/anomaly_scores/from_cost.py
  skchange/base/base_detector.py
  skchange/base/base_interval_scorer.py
  skchange/change_detectors/base.py
  skchange/change_detectors/moving_window.py
  skchange/change_detectors/pelt.py
  skchange/change_detectors/seeded_binseg.py
  skchange/change_scores/cusum.py
  skchange/change_scores/from_cost.py
  skchange/change_scores/multivariate_gaussian_score.py
  skchange/costs/base.py
  skchange/costs/gaussian_cost.py
  skchange/costs/l2_cost.py
  skchange/costs/multivariate_gaussian_cost.py
Labels: documentation
